sqlite: &sqlite
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  database: db/development.sqlite3
  <<: *sqlite

test:
  database: ":memory:"
  verbosity: quiet
  <<: *sqlite

production:
  database: db/heroku.sqlite3
  <<: *sqlite
#  not ready for production
#  Set up production database in unicode http://oldwiki.rubyonrails.org/rails/pages/HowToUseUnicodeStrings
